pipelines:
  default: 
  - parallel: &buildstep        
    - step:
        name: node test
        caches:
        - node
        image: node:8
        script:
        - npm install
        - export PATH="node_modules/.bin:$PATH"
        - npm test
